SELECT * FROM T_SIP_FUNCIONARIO;
-- Verificar todos os funcionarios 

-- Atualizar duas ou mais colunas em um comando de atualizacao
-- alterar nome e dt nascimento de um funcionario ESPECIFICO
UPDATE T_SIP_FUNCIONARIO
    SET NM_FUNCIONARIO = 'Luiz Alves',
        DT_NASCIMENTO = TO_DATE('24/08/1974','DD/MM/YYYY')
    WHERE NR_MATRICULA = 1026; -- FUNDAMENTAL USAR O WHERE P/ FILTRAR  E NAO SELECIONAR TODOS OS FUNCIONARIOS
SELECT * FROM T_SIP_FUNCIONARIO WHERE NR_MATRICULA = 1026;

-- AUMENTAR O SALARIO DE TODOS OS FUNCIONARIOS
UPDATE T_SIP_FUNCIONARIO
    SET VL_SALARIO_MENSAL = VL_SALARIO_MENSAL * 1.05;
SELECT *FROM T_SIP_FUNCIONARIO
