-- Excluir projetos iniciados ate 31/12/2020
DELETE FROM T_SIP_PROJETO
    WHERE DT_INICIO <= TO_DATE('31/12/2020','DD/MM/YYYY');
SELECT * FROM T_SIP_PROJETO;
-- Exclui TUDO DO T_SIP_PROJETO, POIS N TEM O WHERE P FILTRAR
DELETE FROM T_SIP_PROJETO;
SELECT * FROM T_SIP_PROJETO;
