-- ERRO DE CHAVE PRIMARIA
INSERT INTO T_SIP_DEPARTAMENTO(CD_DEPTO, NM_DEPTO, SG_DEPTO)
    VALUES(1, 'FINANCEIRO', 'FNC');  
SELECT * FROM T_SIP_DEPARTAMENTO;
-- ERRO DE VIOLACAO DA CHAVE PRIMARIA
INSERT INTO T_SIP_DEPARTAMENTO
    VALUES(2, 'Teste', 'TST');
-- Restricao exclusiva de chave primaria
SELECT * FROM T_SIP_DEPARTAMENTO;

-- ERRO DE CONSTRAINT
INSERT INTO T_SIP_DEPARTAMENTO
    VALUES(3, 'Financeiro', 'FNC');
-- Restricao exclusiva UN_SIP_DEPTO_NOME

-- ERRO DE VIOLACAO DE CHAVE ESTRANGEIRA
INSERT INTO T_SIP_FUNCIONARIO
     VALUES  (12346, 99 ,'JOSÉ CLEMENTE', 
              TO_DATE('21/03/1987','DD/MM/YYYY'),
              TO_DATE('04/05/2020','DD/MM/YYYY'),
              'AVENIDA PAULISTA, 1900 - 10o. ANDAR', 
              3541.55);
-- ERRO REFERENTE A PRECISÃO DO CAMPO
INSERT INTO T_SIP_DEPARTAMENTO 
     VALUES (12345, 'DEPTO TESTE', 'TST');
     
-- ERRO DE TIPO DE DADOS INVÁLIDO
INSERT INTO T_SIP_DEPARTAMENTO 
     VALUES ('XXX', 'DEPTO TESTE', 'TST');

-- ERRO DE VALORES INSUFICIENTES PARA A INSERÇÃO
INSERT INTO T_SIP_DEPARTAMENTO VALUES (222, 'DEPTO TESTE'); 

-- ERRO DE VALORES DEMAIS PARA A INSERÇÃO
INSERT INTO T_SIP_DEPARTAMENTO 
     VALUES (5, 'DEPTO TESTE', 'TST', 'XXX');   
