-- Consulta 01
SELECT CD_PROJETO, NM_PROJETO, 
DT_INICIO, DT_TERMINO "Finalizado em:"
    FROM T_SIP_PROJETO
    WHERE DT_TERMINO IS NOT NULL AND 
    DT_TERMINO >= TO_dATE('01/08/2018','DD/MM/YYYY')
    ORDER BY DT_TERMINO DESC;
    
