-- CONSULTANDO TODAS AS LINHAS E COLUNAS DA TABELA FUNCIONARIO
SELECT * FROM T_SIP_FUNCIONARIO; -- N E UMA BOA PRATICA

-- Especificando as colunas que deseja consultar e recuperando -- todas as linhas da tabela FUNCIONARIO
SELECT NR_MATRICULA, NM_FUNCIONARIO, VL_SALARIO_MENSAL
  FROM T_SIP_FUNCIONARIO;
  
-- Especificando as colunas que deseja consultar e filtrando --- as linhas da tabela FUNCIONARIO.
SELECT NR_MATRICULA, CD_DEPTO, 
       NM_FUNCIONARIO, VL_SALARIO_MENSAL
  FROM T_SIP_FUNCIONARIO
 WHERE CD_DEPTO = 3;
 
 -- RECUPERANDO OS DEPARTAMENTOS (SEM REPETIÇÃO) QUE POSSUEM 
-- FUNCIONARIOS
SELECT DISTINCT CD_DEPTO FROM T_SIP_FUNCIONARIO;
-- OU
SELECT UNIQUE CD_DEPTO FROM T_SIP_FUNCIONARIO;

-- EXEMPLO DE CONSULTA UTILIZANDO OPERADORES ARITMÉTICOS
SELECT NR_MATRICULA, NM_FUNCIONARIO, 
       VL_SALARIO_MENSAL,
       VL_SALARIO_MENSAL * 1.05
  FROM T_SIP_FUNCIONARIO;
  
  -- EXEMPLOS DE APELIDOS DE COLUNAS
SELECT NR_MATRICULA, 
 NM_FUNCIONARIO FUNCIONARIO, 
 VL_SALARIO_MENSAL "SALÁRIO MENSAL",
 VL_SALARIO_MENSAL * 1.05 AS "SALÁRIO REAJUSTADO"
  FROM T_SIP_FUNCIONARIO;
  
  -- APRESENTANDO RESULTADOS DE FORMA ORDENADA
-- ORDER BY ASC
  SELECT  CD_DEPTO, NM_DEPTO
    FROM T_SIP_DEPARTAMENTO
ORDER BY NM_DEPTO;

-- APRESENTANDO RESULTADOS DE FORMA ORDENADA
-- ORDER BY UTILIZANDO NÚMEROS QUE REPRESENTAM 
-- A POSIÇÃO DAS COLUNAS NO SELECT
  SELECT NR_MATRICULA, CD_DEPTO, 
   NM_FUNCIONARIO, VL_SALARIO_MENSAL  
    FROM T_SIP_FUNCIONARIO 
ORDER BY 2 ASC, 4 DESC;

-- APRESENTANDO RESULTADOS DE FORMA ORDENADA
-- ORDER BY UTILIZANDO O APELIDO DAS COLUNAS
  SELECT NR_MATRICULA        "MATRICULA", 
         NM_FUNCIONARIO      "NOME ",
         VL_SALARIO_MENSAL   "SALÁRIO MENSAL",
         VL_SALARIO_MENSAL * 1.05 "SALÁRIO REAJUSTADO"
    FROM T_SIP_FUNCIONARIO 
ORDER BY "SALÁRIO REAJUSTADO" DESC;

